### ISSUE TITLE
URI passed to httpc:request/5 can fail to parse on OTP 21

### ISSUE THREAD

**Issue by whitfin** [rabbitmq/rabbitmq-management-exchange#5]
I can't share much of this because it's all private, but here's a crash:

```
 {function_clause,
    [{uri_string,parse,
         [{error,invalid_uri,":"}],
         [{file,"uri_string.erl"},{line,337}]},
     {httpc,request,5,[{file,"httpc.erl"},{line,179}]},
     {rabbit_exchange_type_management,handle_rpc,6,
         [{file,"src/rabbit_exchange_type_management.erl"},{line,90}]},
     {rabbit_exchange_type_management,'-route/2-lc$^0/1-0-',6,
         [{file,"src/rabbit_exchange_type_management.erl"},{line,61}]},
     {rabbit_exchange_type_management,route,2,
         [{file,"src/rabbit_exchange_type_management.erl"},{line,61}]},
     {rabbit_exchange,route1,3,[{file,"src/rabbit_exchange.erl"},{line,397}]},
     {rabbit_exchange,route,2,[{file,"src/rabbit_exchange.erl"},{line,387}]},
     {rabbit_channel,handle_method,3,
         [{file,"src/rabbit_channel.erl"},{line,1138}]}]}
```

If you use OTP 21 and use this exchange, the reply crashes due to something with the internal URI.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
I'm afraid we can't do much without a single step to reproduce. The URI is somehow set to `:` which is definitely not a valid URI.

Please have some consideration for the maintainers' time and share at least some basic steps to reproduce.

**Comment by whitfin** [comment]
@michaelklishin to approach this in that way is extremely unfriendly and to value your time over mine is not in the spirit of OSS. 

You're right that the URI appears to be set to `:`, but looking at the code quickly shows that this URI is constructed by this exchange (and should not be dismissed just as me doing something wrong). That's why this issue is here; there is clearly a bug (a crash!) in this library.

I intend to look into this further, I simply filed the issue to track it in case someone already knows of a potential fix. It's not exactly beginner-friendly to get started with adding patches to these plugins. I'm working on a basic reproduction now; but I'd be surprised if event the tests in this repo didn't catch it.

**Comment by michaelklishin** [comment]
@whitfin our team gets a lot of these "obvious bugs" that turn out not to be exactly obvious (or bugs) a lot of the time. Sorry but if there are no details, we close issues. I consider an issue without any details but claims of "an obvious bug" to be disrespectful of the maintainer's time. You get this software for free. Help improve it by at least providing relevant information or maintain and use your own fork.

**Comment by michaelklishin** [comment]
The path passed to `httpc` is [taken from the routing keys](https://github.com/rabbitmq/rabbitmq-management-exchange/blob/master/src/rabbit_exchange_type_management.erl#L61) (thanks to the  [`CC` and `BCC` headers](https://www.rabbitmq.com/sender-selected.html) there can be more than one) and routing keys are provided by the publisher and not this plugin.

This plugin now has a couple more tests that all pass on OTP 21 just like the original one did. They don't cover much but they do demonstrate that it is not an obvious OTP 21 incompatibility.
